export const data = [
  {
    id: 1,
    name: "Dibbert LLC",
    email: "raufderhar@gmail.com",
    vat: "2741610243",
    phone: "+14438451828",
    country: "El Salvador",
    website: "http://hoeger.com",
    image: "/logo-1.svg",
  },
  {
    id: 2,
    name: "Marks-Will",
    email: "garnett.hoppe@braun.net",
    vat: "8572697550",
    phone: "+14638188000",
    country: "Barbados",

    website: "http://baumbach.org",
    image: "/logo-2.svg",
  },
  {
    id: 3,
    name: "Jacobson, Davis and D'Amore",
    email: "lkeeling@legros.com",
    vat: "92574815160",
    phone: "+15809344451",
    country: "Netherlands",

    website: "http://hammes.biz",
    image: "/logo-3.svg",
  },
  {
    id: 4,
    name: "Cartwright-Jacobs",
    email: "fortiz@runte.com",
    vat: "66474349",
    phone: "+12836621870",
    country: "Cameroon",
    website: "http://hamill.org",
    image: "/logo-4.svg",
  },
  {
    id: 5,
    name: "Ratke, Kassulke and Jaskolski",
    email: "johathan.price@koss.com",
    vat: "886245776",
    phone: "+15759769114",
    country: "Bolivia",

    website: "http://bode.com",
    image: "/logo-5.svg",
  },
  {
    id: 6,
    name: "Legros Group",
    email: "flossie92@greenholt.com",
    vat: "28751463",
    phone: "+15038010697",
    country: "Norfolk Island",
    website: "http://conn.net",
    image: "/logo-6.svg",
  },
];
